# syntax=docker/dockerfile:1.4
FROM ubuntu:noble # nvidia/cuda:12.3.1-devel-ubuntu24.04
WORKDIR /workspace
VOLUME /workspace
ARG WUK_INSTALL_PREFIX=/workspace/HFuse_build
ARG SCC_OPT=/workspace
ENV SCC_SETUP_ENV=${SCC_OPT}/sysu-scc-spack-repo/share/sysu-scc-spack-repo/setup-env.sh
COPY . /workspace/HFuse/
RUN <<EOF

apt-get update -y
apt-get upgrade -y
apt-get install --no-install-recommends -y \
    python3 patch tar gzip unzip bzip2 xz-utils \
    file git ca-certificates make bash \
    clang llvm-dev libclang-dev cmake ninja-build
apt-get autoremove -y
apt-get clean -y
rm -rf /var/lib/apt/lists/*

cd ${SCC_OPT}
git clone --depth=1 https://github.com/SYSU-SCC/sysu-scc-spack-repo
bash $(dirname $SCC_SETUP_ENV)/init-env.sh v0.21.0
. ${SCC_SETUP_ENV}
spack install -y --fail-fast cuda@12.3.0%clang target=$(arch)
spack gc -y
spack clean -ab

rm -rf ${WUK_INSTALL_PREFIX}
cd /workspace/HFuse
cmake -G Ninja \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_PREFIX_PATH="$(llvm-config --cmakedir);$(llvm-config --cmakedir)../clang" \
    -DCMAKE_INSTALL_PREFIX=${WUK_INSTALL_PREFIX} \
    -B ${WUK_INSTALL_PREFIX}/build
cmake --build ${WUK_INSTALL_PREFIX}/build -j
cmake --build ${WUK_INSTALL_PREFIX}/build -t install

EOF
