# syntax=docker/dockerfile:1.4
FROM wukan0621/sccenv
WORKDIR /workspace
VOLUME /workspace
ARG WUK_INSTALL_PREFIX=/workspace/HFuse-build
COPY . /workspace/HFuse/
RUN <<EOF

apt-get update -y
apt-get upgrade -y
apt-get autoremove -y
apt-get clean -y
rm -rf /var/lib/apt/lists/*

. $SCC_SETUP_ENV
spack install -y --fail-fast cmake@3.27.7%gcc@7.5.0 llvm@17.0.4%gcc@7.5.0+clang~libomptarget targets=nvptx cuda@12.2.1%gcc@7.5.0
spack clean -ab

spack load cmake@3.27.7%gcc@7.5.0 llvm@17.0.4%gcc@7.5.0+clang~libomptarget targets=nvptx cuda@12.2.1%gcc@7.5.0

rm -rf ${WUK_INSTALL_PREFIX}
cmake \\
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \\
    -DCMAKE_C_COMPILER=clang \\
    -DCMAKE_CXX_COMPILER=clang++ \\
    -DCMAKE_PREFIX_PATH="$(llvm-config --cmakedir);$(llvm-config --cmakedir)../clang" \\
    -DCMAKE_INSTALL_PREFIX=${WUK_INSTALL_PREFIX} \\
    -B ${WUK_INSTALL_PREFIX}/build
cmake --build ${WUK_INSTALL_PREFIX}/build -j
cmake --build ${WUK_INSTALL_PREFIX}/build -t install

EOF