# syntax=docker/dockerfile:1.4
FROM wukan0621/sccenv
RUN <<EOF

apt-get update -y
apt-get upgrade -y
apt-get autoremove -y
apt-get clean -y
rm -rf /var/lib/apt/lists/*

. $SCC_SETUP_ENV
spack install -y --fail-fast llvm@10.0.1+clang+cuda cuda_arch=61,70,80 ^ cuda@11.5.2
spack clean -ab

EOF